# Generated by Django 5.1.2 on 2024-11-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_polls_quest_pub_dat_5d0c19_idx'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.CheckConstraint(condition=models.Q(('votes__gte', 0)), name='votes_non_negative'),
        ),
    ]
